services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: sistema-municipal-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_municipal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./base_datos_sistema_municipal/bd.sql:/docker-entrypoint-initdb.d/bd.sql:ro
    networks:
      - sistema-network-dev

  # Spring Boot Backend
  backend:
    image: sistema-backend:v2
    container_name: sistema-municipal-backend-dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sistema_municipal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql-db
    networks:
      - sistema-network-dev
    volumes:
      - backend_uploads_dev:/app/uploads

  # Angular Frontend (Development)
  frontend:
    build:
      context: ./sistema_municipal_frontend
      dockerfile: Dockerfile.dev
    container_name: sistema-municipal-frontend-dev
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./sistema_municipal_frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sistema-network-dev

volumes:
  mysql_data_dev:
  backend_uploads_dev:

networks:
  sistema-network-dev:
    driver: bridge
